# The URL the site will be built for
base_url = "https://thinking-with-computers.github.io"
output_dir = "docs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hikari"

title = "Thinking with Computers"
description = "On the history of interactive programming"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true

[extra]
# Put all your custom variables here

author = "Thinking with Computers"
author_bio = "Thinking with Computers is a SSHRC-funded history of computing project at the University of Toronto, focusing on the design of interactive programming in the 1970s. The PI is Scott Richmond and Matthew Nish-Lapidus is a collaborator. This is our research blog."
twitter = false
github = "thinking-with-computers"
instagram = false
enable_mathjax = false
